//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UIforETW.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_UIFORETW_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_SETTINGS                    129
#define IDR_TRACESCONTEXTMENU           130
#define IDR_ACCELERATORS                131
#define IDR_RENAMEACCELERATORS          132
#define IDR_NOTESACCELERATORS           133
#define IDR_NONNOTESACCELERATORS        134
#define IDR_TRACESACCELERATORS          134
#define IDC_STARTTRACING                1000
#define IDC_SAVETRACEBUFFERS            1001
#define IDC_STOPTRACING                 1002
#define IDC_COMPRESSTRACE               1004
#define IDC_CPUSAMPLINGCALLSTACKS       1005
#define IDC_CONTEXTSWITCHCALLSTACKS     1006
#define IDC_OUTPUT                      1007
#define IDC_FASTSAMPLING                1008
#define IDC_SHOWCOMMANDS                1009
#define IDC_SHOWCOMMANDS2               1010
#define IDC_DIRECTXTRACING              1010
#define IDC_GPUTRACING                  1010
#define IDC_TRACINGMODE                 1011
#define IDC_INPUTTRACING                1012
#define IDC_TRACELIST                   1013
#define IDC_TRACENOTES                  1014
#define IDC_ABOUT                       1015
#define IDC_SETTINGS                    1016
#define IDC_INPUTTRACING_LABEL          1017
#define IDC_HEAPEXE                     1018
#define IDC_TRACEDIR                    1019
#define IDC_EXTRAPROVIDERS              1019
#define IDC_EXTRAKERNELFLAGS            1019
#define IDC_CLRTRACING                  1019
#define IDC_BUTTON1                     1020
#define IDC_EXTRASTACKWALKS             1020
#define IDC_TEMPTRACEDIR                1021
#define IDC_HEAPEXE2                    1021
#define IDC_WSMONITOREDPROCESSES        1021
#define IDC_BUTTON2                     1022
#define IDC_COPYSTARTUPPROFILE          1022
#define IDC_COMBO1                      1023
#define IDC_BUFFERSIZES                 1023
#define IDC_TRACENAMEEDIT               1024
#define IDC_COPYSTARTUPPROFILE2         1024
#define IDC_COPYSYMBOLDLLS              1024
#define IDC_UNUSEDDEFAULTBUTTON         1025
#define IDC_EXTRASTACKWALKS2            1025
#define IDC_EXTRAUSERMODEPROVIDERS      1025
#define IDC_CHROMEDEVELOPER             1026
#define IDC_CHECK2                      1027
#define IDC_AUTOVIEWTRACES              1027
#define IDC_CHECK1                      1028
#define IDC_HEAPSTACKS                  1028
#define IDC_VIRTALLOCSTACKS             1029
#define IDC_VIRTUALALLOCSTACKS          1029
#define IDC_CHROMEDLLPATH               1030
#define IDC_EXTRAUSERMODEPROVIDERS2     1030
#define IDC_PERFORMANCECOUNTERS         1030
#define IDC_BUILDDATE                   1031
#define IDC_EXPENSIVEWS                 1031
#define IDC_CHROME_CATEGORIES           1033
#define IDC_WS_MONITOR_STATIC           1034
#define IDC_CHECK3                      1035
#define IDC_CHECKFORNEWVERSIONS         1035
#define IDC_TRACESIZE                   1036
#define IDC_CHECKFORNEWVERSIONS2        1036
#define IDC_TRACEJAVASCRIPT             1036
#define IDC_SELECT_PERF_COUNTERS        1037
#define IDC_CHECK4                      1038
#define IDC_USE_OTHER_KERNEL_LOGGER     1038
#define IDC_USE_OTHER_KERNEL_LOGGER2    1039
#define IDC_RECORD_PRE_TRACE            1039
#define IDC_RECORD_PRE_TRACE2           1040
#define IDC_IDENTIFY_CHROME_CPU         1040
#define IDC_BACKGROUND_MONITORING       1041
#define IDC_RECORD_TRACE_COMMAND        1042
#define ID_TRACES_DELETETRACE           32772
#define ID_TRACES_COMPRESSTRACE         32773
#define ID_TRACES_COMPRESSTRACES        32774
#define ID_TRACES_BROWSEFOLDER          32775
#define ID_TRACES_STRIPCHROMESYMBOLS    32776
#define ID_TRACES_TRACEPATHTOCLIPBOARD  32777
#define ID_TRACES_ZIPCOMPRESSTRACE      32778
#define ID_TRACES_RENAMETRACE           32779
#define ID_TRACES_ZIPCOMPRESSALLTRACES  32780
#define ID_ENDRENAME                    32781
#define ID_RENAME                       32782
#define ID_ESCKEY                       32783
#define ID_TRACES_OPENTRACEINGPUVIEW    32787
#define ID_SELECTALL                    32790
#define ID_DELETETRACE                  32791
#define ID_VIEWTRACE                    32792
#define ID_COPYTRACENAME                32794
#define ID_RENAMEFULL                   32798
#define ID_TRACES_OPENTRACEIN10         32800
#define ID_TRACES_OPENTRACEIN10WPA      32801
#define ID_ACCELERATOR32802             32802
#define ID_PASTEOVERRIDE                32805
#define ID_TRACES_IDENTIFYCHROMEPROCESSES 32807
#define ID_TRACES_OPENTRACEINEXPERIENCEANALYZER 32808
#define ID_TRACES_SCRIPTS               32809
#define ID_SCRIPTS_CREATEFLAMEGRAPH     32810
#define ID_TRACES_TRACECOMPRESSION      32811
#define ID_SCRIPTS_IDENTIFYCHROMEPROCESSESWITHCPU 32812
#define ID_IDENTIFYCHROMEPROCESSESWITHCPU 32813
#define ID_TRACES_IDENTIFYCHROMEPROCESSESWITHCPU 32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
