// UIforETW.idl : IDL source for UIforETW
//

// This file will be processed by the MIDL tool to
// produce the type library (UIforETW.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(2CD11978-FF8A-4144-8669-838CBD610C37),
	version(1.0)	
]
library UIforETWLib
{
	importlib("stdole2.tlb");
};
